---
# tasks file for roles/iis
- name: Install IIS
  win_feature: 
    name: 
      - Web-Server
      - Web-Common-Http
    include_sub_features: True
    include_management_tools: True
    state: present

- name: Install Net.Framework
  win_feature:
    name: NET-Framework-Core
    source: C:\Temp\iso\sources\sxs
    state: present

